kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-dev-test
nodes:
  - role: control-plane
    image: kindest/node:v1.32.0
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443