apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: argocd-namespace-generator
    namespace: applicationset-namespace-generator-plugin