apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-namespace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-namespace-generator
  template:
    metadata:
      labels:
        app: argocd-namespace-generator
    spec:
      serviceAccountName: argocd-namespace-generator
      containers:
        - name: argocd-namespace-generator
          image: ghcr.io/estenrye/argocd-namespace-generator:0.1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /var/run/argo/token
              name: token
              subPath: token
      volumes:
        - name: token
          secret:
            secretName: argocd-namespace-generator