apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.11/manifests/install.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding