apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-generator-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secret-reader
subjects:
- kind: ServiceAccount
  name: argocd-namespace-generator
  namespace: argocd