apiVersion: v1
kind: Service
metadata:
  name: plugin
  namespace: applicationset-namespace-generator-plugin
spec:
  selector:
    app: argocd-namespace-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30080
  type: NodePort